### ISSUE TITLE
Using against a private repo

### ISSUE THREAD

**Issue by cconstab** [atsign-company/dump_cards#3]
**Is your feature request related to a problem? Please describe.**
When running this against a private repo what permissions does my person token need ?
It also seems that not all the py scripts take the option of the org e.g ./list_sprintplanning_columns.py

**Describe the solution you'd like**
To be able to run against a private repo as this tool is very useful

**Describe alternatives you've considered**
We had to cut and paste this morning.. Worked fine but not very Dev friendly :-)
**Additional context**
Perhaps an uber command line to bring all the parts together would be nice in time.. 

Maybe the functionality already exists ? I just could not find it before the cut/paste beat me to it ?

**Comment by cpswan** [comment]
`list_projects.py` was hard coded to atsign_foundation, but I've modified it to take the org as an argument.

We now also have:

* `list_company.py` which is hard coded to atsign-company
* `list-foundation.py` which is hard coded to atsign-foundation

So to get the csv for the marketing board PR13 column:

`./list_company.py`

```
5640050 1 @ Production Infrastructure Build out and Go LIve!
5640153 2 @protocol features roadmap
5640288 3 @persona features roadmap
5640319 4 @demos
5640333 5 @libraries
6016491 6 Sprint Planning - Jagan and Murali
6065970 7 Master Bug Project Board
11705603 8 Atmosphere Board
11705635 9 Web Registrar Board
12388324 11 Wavi Rebranding and v2
12478765 12 App Issues
12553473 14 FHIR @hack : July 9-11 2021
12587318 15 Marketing and GTM
```

`./list_project_columns.py 12587318 atsign-company`

```
14564544 Events | Comms
14566749 Social Media | Community
14564545 Apps | Content
14566719 PR13 18 SP's | 29"s
```

```bash
./dump_project_cards.py 14566719
cat 14566719.csv
```

```
Issue Key,Summary,Description,Acceptance Criteria,Story Points
4,Company Messaging and Strategy,,,
5,Enhanced Content / SEO Strategy,,,
7,Educational Content,,,
2,Update Nomanclature,,,
13,Social Media Tool Research,,,
10,Metrics/Analytics,,,
8,@buzz,,,
11,PR,,,
15,Target Training Organizations,,,
14,Early Access Program,,,
```
