### ISSUE TITLE
Read the GITHUB_API_TOKEN from a .env file

### ISSUE THREAD

**Issue by iagotito** [atsign-company/dump_cards#8]
**Is your feature request related to a problem? Please describe.**
I don't like to export a variable in my `.zshenv` to all my system when its only going to be useful in one specifc project, and it's a bit annoying have to run the `api_keys.sh` described in the README, and it's even worse define it when I call the script.

**Describe the solution you'd like**
This variable could be stored in a `.env` file specific to the project. So, if you want to define it in your dotfiles or in the .env, the choice is yours.

**Describe alternatives you've considered**
It can be stored in another file such as json or yaml, if you don't want to add the `python_dotenv` as a dependency, but I think the .env is the pattern to it.

**Comment by cpswan** [comment]
Thanks @iagotito 

If you have a PR for this then I'd be happy to merge it.

**Comment by cpswan** [comment]
Closed by #9
